#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..
if [ ! -e bin/rancher-cni-bridge ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin
tar cvzf ../dist/artifacts/rancher-cni-bridge-${VERSION}.tar.gz .
